// lib/core/widgets/math/editor/math_expression/utils/constants.dart
class Constants {
  static const List<String> symbolCategories = [
    'أساسيات',
    'حروف',
    'علاقات',
    'منطق ومجموعات',
    'عمليات',
    'يوناني',
    'دوال',
    'احتمالات',
    'كيمياء',
    'مركبات',
    'قوالب',
  ];

  static const Map<String, List<String>> symbols = {
    'أساسيات': [
      '+', '-', '=', r'\neq',
      '(', ')', '[', ']', r'\{', r'\}',
      r'\langle', r'\rangle',
      r'\space', r'\quad',
      ',', '.', ':', r'\%',
      r'\cdot', r'\cdots', r'\vdots', r'\ddots',
      r'\ldots', r'| |', r'\|',
    ],
    'حروف': [
      'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
      'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
      'u', 'v', 'w', 'x', 'y', 'z',
      'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
      'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
      'U', 'V', 'W', 'X', 'Y', 'Z',
      r'\mathbb{N}', r'\mathbb{Z}', r'\mathbb{Q}', r'\mathbb{R}', r'\mathbb{C}',
    ],
    'علاقات': [
      '<', '>', r'\leq', r'\geq', r'\ll', r'\gg',
      r'\sim', r'\simeq', r'\approx', r'\equiv', r'\cong',
      r'\parallel', r'\perp', r'\mid', r'\nmid',
      r'\propto', r'\asymp',
    ],
    'منطق ومجموعات': [
      r'\in', r'\notin', r'\ni',
      r'\subset', r'\supset', r'\subseteq', r'\supseteq',
      r'\emptyset', r'\complement',
      r'\forall', r'\exists', r'\nexists',
      r'\neg', r'\lor', r'\land', r'\implies', r'\iff',
      r'\therefore', r'\because', r'\infty',
    ],
    'عمليات': [
      r'\times', r'\div', r'\pm', r'\mp',
      r'\ast', r'\star', r'\circ', r'\bullet',
      r'\cap', r'\cup', r'\setminus',
      r'\int', r'\iint', r'\sum', r'\prod',
      r'\partial', r'\nabla',
      r'\rightarrow', r'\leftarrow', r'\Rightarrow', r'\Leftarrow',
    ],
    'يوناني': [
      r'\alpha', r'\beta', r'\gamma', r'\delta',
      r'\epsilon', r'\varepsilon', r'\zeta', r'\eta', r'\theta',
      r'\iota', r'\kappa', r'\lambda', r'\mu', r'\nu', r'\xi',
      r'\pi', r'\rho', r'\sigma', r'\tau', r'\upsilon', r'\phi',
      r'\chi', r'\psi', r'\omega',
      r'\Gamma', r'\Delta', r'\Theta', r'\Lambda', r'\Xi',
      r'\Pi', r'\Sigma', r'\Upsilon', r'\Phi', r'\Psi', r'\Omega',
    ],
    'دوال': [
      r'\sin', r'\cos', r'\tan', r'\cot', r'\sec', r'\csc',
      r'\arcsin', r'\arccos', r'\arctan',
      r'\sinh', r'\cosh', r'\tanh',
      r'\ln', r'\log', r'\exp', r'\lim', r'\max', r'\min',
    ],
    'احتمالات': [
      r'P(A)', r'P(B)', r'P(A \cap B)', r'P(A \cup B)',
      r'P(A|B)', r'E(X)', r'Var(X)', r'\sigma', r'\mu',
      r'\bar{x}', r'\hat{p}', r'\chi^2',
    ],
    'كيمياء': [
      'H', 'He', 'Li', 'Be', 'B', 'C', 'N', 'O', 'F', 'Ne',
      'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'Cl', 'Ar', 'K', 'Ca',
      'Fe', 'Cu', 'Zn', 'Ag', 'Au', 'Hg', 'Pb', 'Sn', 'I', 'Br',
      r'\rightarrow', r'\rightleftharpoons', r'\uparrow', r'\downarrow',
      '+', r'\Delta', r'(s)', r'(l)', r'(g)', r'(aq)',
    ],
    'مركبات': [
      r'H_2O', r'CO_2', r'NaCl', r'HCl', r'H_2SO_4', r'NaOH',
      r'CH_4', r'C_6H_{12}O_6', r'NH_3', r'CaCO_3', r'KMnO_4',
      r'O_2', r'H_2', r'N_2', r'Cl_2', r'SO_2', r'NO_2',
    ],
    'قوالب': [
      r'\frac{a}{b}', r'\sqrt{x}', r'\sqrt[n]{x}', r'x^n', r'x_n',
      r'\int_{a}^{b} x dx', r'\sum_{i=1}^{n} i',
      r'\lim_{x \to a} f(x)', r'\binom{n}{k}',
      r'x = \frac{-b \pm \sqrt{b^2 - 4ac}}{2a}',
      r'E = mc^2', r'A = \pi r^2', r'a^2 + b^2 = c^2',
    ],
  };

  static const Map<String, String> symbolDescriptions = {
    '+': 'جمع',
    '-': 'طرح',
    '=': 'يساوي',
    r'\neq': 'لا يساوي',
    r'\alpha': 'ألفا',
    r'\beta': 'بيتا',
    r'\gamma': 'جاما',
    r'\delta': 'دلتا',
    r'\pi': 'باي',
    r'\sum': 'سيجما / مجموع',
    r'\int': 'تكامل',
    r'\infty': 'مالانهاية',
    r'\sin': 'جا / Sine',
    r'\cos': 'جتا / Cosine',
    r'\tan': 'ظا / Tangent',
    r'H_2O': 'ماء',
    r'CO_2': 'ثاني أكسيد الكربون',
    r'NaCl': 'ملح الطعام',
    r'HCl': 'حمض الهيدروكلوريك',
    r'NaOH': 'هيدروكسيد الصوديوم',
  };
}
