// lib/core/widgets/math/editor/math_expression/utils/constants.dart
class Constants {
  static const List<String> symbolCategories = [
    'أرقام',
    'أساسيات',
    'كسور',
    'أسس وجذور',
    'تكاملات',
    'تجميعات',
    'أقواس مخصصة',
    'حالات ومصفوفات',
    'تمييز',
    'تفاضلات',
    'دوال',
    'حروف',
    'يوناني',
    'علاقات',
    'منطق ومجموعات',
    'عمليات',
    'احتمالات',
    'كيمياء',
    'مركبات',
  ];

  static const Map<String, List<String>> symbols = {
    'أرقام': [
      '1',
      '2',
      '3',
      '4',
      '5',
      '6',
      '7',
      '8',
      '9',
      '0',
      '.',
      ',',
      '%',
      r'\pi',
      r'e',
      r'i',
    ],
    'أساسيات': [
      '+',
      '-',
      r'\times',
      r'\div',
      '=',
      r'\ne',
      '(',
      ')',
      '[',
      ']',
      r'\{',
      r'\}',
      r'\pm',
      r'\mp',
      r'<',
      '>',
      r'\leq',
      r'\geq',
      r'\infty',
      r'\approx',
      r'\sim',
      r'^\circ',
      r'^\circ\text{C}',
      r'^\circ\text{F}',
    ],
    'كسور': [
      r'\frac{\square}{\square}',
      r'\square/\square',
      r'\tfrac{\square}{\square}',
      r'\frac{dy}{dx}',
      r'\frac{\Delta y}{\Delta x}',
      r'\frac{\partial y}{\partial x}',
      r'\frac{\delta y}{\delta x}',
      r'\frac{\pi}{2}',
    ],
    'أسس وجذور': [
      r'\square^{\square}',
      r'\square_{\square}',
      r'\square_{\square}^{\square}',
      r'{}^{\square}_{\square}\square',
      r'\sqrt{\square}',
      r'\sqrt[\square]{\square}',
      r'\sqrt[2]{a}',
      r'\sqrt[3]{a}',
    ],
    'تكاملات': [
      r'\int \square dx',
      r'\int_{\square}^{\square} \square dx',
      r'\iint \square dA',
      r'\iint_{\square} \square dA',
      r'\iiint \square dV',
      r'\oint \square dl',
      r'\oiint \square dS',
      r'\oiiint \square dV',
    ],
    'تجميعات': [
      r'\sum_{\square=\square}^{\square} \square',
      r'\sum \square',
      r'\prod_{\square=\square}^{\square} \square',
      r'\prod \square',
      r'\coprod_{\square}^{\square}',
      r'\bigcap_{\square}^{\square}',
      r'\bigcup_{\square}^{\square}',
      r'\biguplus_{\square}^{\square}',
      r'\bigvee_{\square}^{\square}',
      r'\bigwedge_{\square}^{\square}',
    ],
    'أقواس مخصصة': [
      r'(\square)',
      r'[\square]',
      r'\{\square\}',
      r'\langle \square \rangle',
      r'|\square|',
      r'\|\square\|',
      r'\lfloor \square \rfloor',
      r'\lceil \square \rceil',
      r']\square[',
      r'[\square[',
      r'(\square|\square)',
      r'\langle \square|\square \rangle',
      r'\square]',
      r'[\square',
      r'\square\}',
      r'\{\square',
    ],
    'حالات ومصفوفات': [
      r'\binom{\square}{\square}',
      r'\begin{cases} \square \\ \square \end{cases}',
      r'\begin{pmatrix} \square & \square \\ \square & \square \end{pmatrix}',
      r'\begin{matrix} \square & \square & \square \\ \square & \square & \square \\ \square & \square & \square \end{matrix}',
      r'\begin{vmatrix} \square & \square \\ \square & \square \end{vmatrix}',
      r'I_2 = \begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}',
      r'I_3 = \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}',
      r'\cdots',
      r'\vdots',
      r'\ddots',
      r'\dots',
    ],
    'تمييز': [
      r'\dot{\square}',
      r'\ddot{\square}',
      r'\dddot{\square}',
      r'\hat{\square}',
      r'\vec{\square}',
      r'\bar{\square}',
      r'\tilde{\square}',
      r'\overline{\square}',
      r'\underline{\square}',
      r'\boxed{\square}',
      r'\boxed{\square^2+\square^2=\square^2}',
      r'\overleftrightarrow{ab}',
      r'\underleftrightarrow{ab}',
      r'\xrightarrow[b]{a}',
      r'\xleftarrow[b]{a}',
    ],
    'تفاضلات': [
      r'dx',
      r'dy',
      r'dz',
      r'dt',
      r'd\theta',
      r'd\phi',
      r'\partial x',
      r'\nabla',
      r'\Delta',
    ],
    'دوال': [
      r'\sin \square',
      r'\cos \square',
      r'\tan \square',
      r'\sin^{-1} \square',
      r'\cos^{-1} \square',
      r'\tan^{-1} \square',
      r'\ln \square',
      r'\log_{\square} \square',
      r'\exp \square',
      r'\lim_{\square \to \square}',
      r'\max_{\square} f(\square)',
      r'\min_{\square} f(\square)',
      r'\lim_{\square \to \infty} (1+\frac{1}{\square})^{\square}',
    ],
    'حروف': [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
      'o',
      'p',
      'q',
      'r',
      's',
      't',
      'u',
      'v',
      'w',
      'x',
      'y',
      'z',
      'A',
      'B',
      'C',
      'D',
      'E',
      'F',
      'G',
      'H',
      'I',
      'J',
      'K',
      'L',
      'M',
      'N',
      'O',
      'P',
      'Q',
      'R',
      'S',
      'T',
      'U',
      'V',
      'W',
      'X',
      'Y',
      'Z',
      r'\mathbb{N}',
      r'\mathbb{Z}',
      r'\mathbb{Q}',
      r'\mathbb{R}',
      r'\mathbb{C}',
    ],
    'علاقات': [
      '<',
      '>',
      r'\leq',
      r'\geq',
      r'\ll',
      r'\gg',
      r'\sim',
      r'\simeq',
      r'\approx',
      r'\equiv',
      r'\cong',
      r'\parallel',
      r'\perp',
      r'\mid',
      r'\nmid',
      r'\propto',
      r'\asymp',
    ],
    'منطق ومجموعات': [
      r'\in',
      r'\not\in',
      r'\ni',
      r'\subset',
      r'\supset',
      r'\subseteq',
      r'\supseteq',
      r'\emptyset',
      r'\complement',
      r'\forall',
      r'\exists',
      r'\nexists',
      r'\neg',
      r'\lor',
      r'\land',
      r'\implies',
      r'\iff',
      r'\therefore',
      r'\because',
      r'\infty',
    ],
    'عمليات': [
      r'\times',
      r'\div',
      r'\pm',
      r'\mp',
      r'\ast',
      r'\star',
      r'\circ',
      r'\bullet',
      r'\cap',
      r'\cup',
      r'\setminus',
      r'\int',
      r'\iint',
      r'\sum',
      r'\prod',
      r'\partial',
      r'\nabla',
      r'\Delta',
      r'\rightarrow',
      r'\leftarrow',
      r'\uparrow',
      r'\downarrow',
      r'\leftrightarrow',
      r'\Rightarrow',
      r'\Leftarrow',
      r'\therefore',
      r'\because',
    ],
    'يوناني': [
      r'\alpha',
      r'\beta',
      r'\gamma',
      r'\delta',
      r'\epsilon',
      r'\varepsilon',
      r'\zeta',
      r'\eta',
      r'\theta',
      r'\iota',
      r'\kappa',
      r'\lambda',
      r'\mu',
      r'\nu',
      r'\xi',
      r'\pi',
      r'\rho',
      r'\sigma',
      r'\tau',
      r'\upsilon',
      r'\phi',
      r'\chi',
      r'\psi',
      r'\omega',
      r'\Gamma',
      r'\Delta',
      r'\Theta',
      r'\Lambda',
      r'\Xi',
      r'\Pi',
      r'\Sigma',
      r'\Upsilon',
      r'\Phi',
      r'\Psi',
      r'\Omega',
    ],
    'احتمالات': [
      r'P(A)',
      r'P(B)',
      r'P(A \cap B)',
      r'P(A \cup B)',
      r'P(A|B)',
      r'E(X)',
      r'Var(X)',
      r'\sigma',
      r'\mu',
      r'\bar{x}',
      r'\hat{p}',
      r'\chi^2',
    ],
    'كيمياء': [
      'H',
      'He',
      'Li',
      'Be',
      'B',
      'C',
      'N',
      'O',
      'F',
      'Ne',
      'Na',
      'Mg',
      'Al',
      'Si',
      'P',
      'S',
      'Cl',
      'Ar',
      'K',
      'Ca',
      'Fe',
      'Cu',
      'Zn',
      'Ag',
      'Au',
      'Hg',
      'Pb',
      'Sn',
      'I',
      'Br',
      r'\rightarrow',
      r'\rightleftharpoons',
      r'\uparrow',
      r'\downarrow',
      '+',
      r'\Delta',
      r'(s)',
      r'(l)',
      r'(g)',
      r'(aq)',
    ],
    'مركبات': [
      r'H_2O',
      r'CO_2',
      r'NaCl',
      r'HCl',
      r'H_2SO_4',
      r'NaOH',
      r'CH_4',
      r'C_6H_{12}O_6',
      r'NH_3',
      r'CaCO_3',
      r'KMnO_4',
      r'O_2',
      r'H_2',
      r'N_2',
      r'Cl_2',
      r'SO_2',
      r'NO_2',
    ],
  };

  static const Map<String, String> symbolDescriptions = {
    '+': 'جمع',
    '-': 'طرح',
    '=': 'يساوي',
    r'\neq': 'لا يساوي',
    r'\alpha': 'ألفا',
    r'\beta': 'بيتا',
    r'\gamma': 'جاما',
    r'\delta': 'دلتا',
    r'\pi': 'باي',
    r'\sum': 'سيجما / مجموع',
    r'\int': 'تكامل',
    r'\infty': 'مالانهاية',
    r'\sin': 'جا / Sine',
    r'\cos': 'جتا / Cosine',
    r'\tan': 'ظا / Tangent',
    r'H_2O': 'ماء',
    r'CO_2': 'ثاني أكسيد الكربون',
    r'NaCl': 'ملح الطعام',
    r'HCl': 'حمض الهيدروكلوريك',
    r'NaOH': 'هيدروكسيد الصوديوم',
    r'\in': 'ينتمي إلى',
    r'\not\in': 'لا ينتمي إلى',
    r'^\circ\text{C}': 'درجة مئوية',
    r'^\circ\text{F}': 'درجة فهرنهايت',
    r'^\circ': 'درجة',
  };
}
